In [2]:
import numpy as np
path="C:/Users/lenovo/Desktop/Classic_machine_learning-master/data_set/datingTestSet.txt"

In [27]:
data=[]
labels=[]
open_file=open(path,mode='r',encoding='gbk')
str=open_file.read()
print(str)
lines=str.split('\n')
print(lines)
for line in lines[:-1]:
    fea=line.split('\t')
    print(fea)
    x1,x2,x3,label=float(fea[0]),float(fea[1]),float(fea[2]),fea[3]
    print(x1,x2,x3,label)
    data.append([x1,x2,x3])
    labels.append(label)
    print(data)
    print(labels)
data=np.array(data)
labels=np.array(labels) 

40920	8.326976	0.953952	largeDoses
14488	7.153469	1.673904	smallDoses
26052	1.441871	0.805124	didntLike
75136	13.147394	0.428964	didntLike
38344	1.669788	0.134296	didntLike
72993	10.141740	1.032955	didntLike
35948	6.830792	1.213192	largeDoses
42666	13.276369	0.543880	largeDoses
67497	8.631577	0.749278	didntLike
35483	12.273169	1.508053	largeDoses
50242	3.723498	0.831917	didntLike
63275	8.385879	1.669485	didntLike
5569	4.875435	0.728658	smallDoses
51052	4.680098	0.625224	didntLike
77372	15.299570	0.331351	didntLike
43673	1.889461	0.191283	didntLike
61364	7.516754	1.269164	didntLike
69673	14.239195	0.261333	didntLike
15669	0.000000	1.250185	smallDoses
28488	10.528555	1.304844	largeDoses
6487	3.540265	0.822483	smallDoses
37708	2.991551	0.833920	didntLike
22620	5.297865	0.638306	smallDoses
28782	6.593803	0.187108	largeDoses
19739	2.816760	1.686209	smallDoses
36788	12.458258	0.649617	largeDoses
5741	0.000000	1.656418	smallDoses
28567	9.968648	0.731232	largeDoses
6808	1.364838	0.640103	small

IOPub data rate exceeded.
The notebook server will temporarily stop sending output
to the client in order to avoid crashing it.
To change this limit, set the config variable
`--NotebookApp.iopub_data_rate_limit`.

Current values:
NotebookApp.iopub_data_rate_limit=1000000.0 (bytes/sec)
NotebookApp.rate_limit_window=3.0 (secs)



In [28]:
data

array([[4.0920000e+04, 8.3269760e+00, 9.5395200e-01],
       [1.4488000e+04, 7.1534690e+00, 1.6739040e+00],
       [2.6052000e+04, 1.4418710e+00, 8.0512400e-01],
       ...,
       [2.6575000e+04, 1.0650102e+01, 8.6662700e-01],
       [4.8111000e+04, 9.1345280e+00, 7.2804500e-01],
       [4.3757000e+04, 7.8826010e+00, 1.3324460e+00]])

In [29]:
max_=np.max(data,axis=0)
print(max_)
min_=np.min(data,axis=0)
print(min_)

[9.1273000e+04 2.0919349e+01 1.6955170e+00]
[0.       0.       0.001156]


In [13]:
new_data=(data-min_)/(max_-min_)

In [14]:
new_data

array([[0.44832535, 0.39805139, 0.56233353],
       [0.15873259, 0.34195467, 0.98724416],
       [0.28542943, 0.06892523, 0.47449629],
       ...,
       [0.29115949, 0.50910294, 0.51079493],
       [0.52711097, 0.43665451, 0.4290048 ],
       [0.47940793, 0.3768091 , 0.78571804]])

In [19]:
from sklearn.model_selection import train_test_split

In [32]:
x_train,x_test,y_train,y_test=train_test_split(new_data,labels,test_size=0.3,random_state=42)

In [21]:
data.shape

(1000, 3)

In [31]:
labels.shape

(1000,)

In [38]:
def KNN_model(x_train,x_test, y_train, y_test,K):
    accuracy = 0
    m,n = x_test.shape 
    for i in range(m):
        data = x_test[i]
        Euclidean_distance = np.power(np.sum((data - x_train)**2,axis=1),0.5)
        sort_k = np.argsort(Euclidean_distance)[:K]  
        get_K_y = y_train[sort_k]
        prob_dict = {}
        for label in get_K_y:
            if label not in prob_dict:
                prob_dict[label] = 1
            else:
                prob_dict[label] += 1

        predict_y = sorted(prob_dict.items(),key=lambda z:z[1],reverse=True)[0][0]
        
        # checking predict y is right?
        if predict_y == y_test[i]:
            accuracy += 1
    print('The test set accurate is {}'.format(accuracy / len(y_test)))

In [39]:
KNN_model(x_train,x_test, y_train, y_test,5)

The test set accurate is 0.9233333333333333
